### ISSUE TITLE
Support for snippets with random elements?

### ISSUE THREAD

**Issue by ghost** [jamshark70/ddwSnippets#2]
An expression like `DDWSnippets.put("foo", "x = { SinOsc.ar }.play")` works, but something like `DDWSnippets.put("foo", { "x = { " ++ [ "Saw", "SinOsc" ].choose ++ ".ar }.play" }.value)` doesn't work the way I would like. My expectation would be that when I insert the latter snippet, it would randomly choose `Saw` or `SinOsc`, but it seems to only insert `Saw`. 

Is there a way to insert snippets with random elements?

**Comment by jamshark70** [comment]
No, not supported.

Tbh it strikes me odd: writing code should generally be deterministic, no? The code itself may perform indeterminate operations, but code *editing* operations I think should not introduce randomness. That is, to me it makes sense to have a SynthDef which, when compiled, randomly chooses from a set of signal paths, but I confess that I don't see presently how it makes sense to type out a SynthDef at one moment that hardcodes a Saw, but the next time you type it, it hardcodes a SinOsc.

Could you explain the use case further?

**Comment by ghost** [comment]
The example I gave was simplified. Ultimately, I wanted to use snippets to generate whole SynthDefs and Patterns with certain randomized elements so they would be different every time. If this is not the tool for that, I understand, and I will stick with the project I have been working on to do something similar.

**Comment by jamshark70** [comment]
OK, I went ahead and supported functions for snippets.
