### ISSUE TITLE
IDE doesn't focus after inserting snippet - macOS

### ISSUE THREAD

**Issue by mtmccrea** [jamshark70/ddwSnippets#3]
On SC 10.3.2, the IDE doesn't focus after inserting snippet.

Here:
https://github.com/jamshark70/ddwSnippets/blob/084143684949c900f591640ede48960bba9a5747/ddwSnippets.sc#L112

Running the command from terminal focuses the SuperCollider UI application (QT?), not the IDE. However changing the above like to:
```
		{ \osx } { { "open -a SuperCollider".unixCmd(postOutput: false) } };
```

works.

... and thanks for writing this utility!

**Comment by jamshark70** [comment]
Hm, is it the SC version or the MacOS version that causes the older osascript command to fail?

Asking because, if it's the OS version rather than the SC version that matters, then making the change as given might break it for other OS versions.

Agreed this is annoying, but I want to be sure the solution will work in the largest number of cases.

**Comment by mtmccrea** [comment]
I tried with SC 3.9.3 and the issue appeared to be the same (one difference being that my suggested fix then opens 3.10.2, which must somehow be my 'default' "SuperCollider").

As for the OS, I'm not sure offhand, though a quick search shows that there are indeed permissions issues with applescripts in 10.14 onward. But the symptom is that it's focusing one SuperCollider app (the interpreter?), but not the IDE. Not sure why `open -a` would be focusing the IDE instead...

If I get access to a machine running an older OS in the coming days I'll give it a try.

**Comment by mtmccrea** [comment]
These both work for 3.9.3 and 3.10.2:

```
{ \osx } { { PathName(PathName(Platform.resourceDir).parentPath).parentPath.openOS } };
```
or
```
{ \osx } { { (String.scDir +/+ "../..").openOS } };
```
Not sure if these are any more robust?

**Comment by dyfer** [comment]
I tested a variation of the above on macos 10.13:

```{ \osx } { { (Platform.resourceDir +/+ "../..").openOS } };```

This works fine and I think is a valid fix.

```"open -a SuperCollider".unixCmd(postOutput: false) ``` should not be used as it depends on the setting which version of SC is set as default.
```String.scDir``` runs the ```Platform``` method so I think running that directly is better.
Regarding the applescript, on macos with recent SC (3.9+?) both sc-ide and sclang processes appear as "SuperCollider" in Activity Monitor (two "SuperCollider" processes). Not sure how to distinguish them nowadays.

@mtmccrea mentioned this quark to me, looks wonderful, thank you!

**Comment by mtmccrea** [comment]
Thanks for testing on the older OS @dyfer !

**Comment by jamshark70** [comment]
Checked in a fix. Thanks for reporting!
