### ISSUE TITLE
On macOS .learn captures key "combination" after pressing the modifier key alone

### ISSUE THREAD

**Issue by dyfer** [jamshark70/ddwSnippets#4]
Hi James,

I wanted to revisit this quark and I encountered this issue: Maybe something changed in Qt on macOS, but currently the logic to choose whether the non-modifier key was selected on macOS does not seem to work anymore and thus `DDWSnippets.learn` learns just the modifier key pressed (i.e. "You pressed ..." message is displayed after pressing a modifier key alone - any of the modifiers).
Here's my workaround in https://github.com/jamshark70/ddwSnippets/blob/master/ddwSnippets.sc#L264: `{ \osx } { { |char, keycode| (keycode >= 62) or: (keycode <= 54) } }`. I'm not sure this is reliable, but it seems the modifiers (left/right shift, alt, ctrl, cmd) emit keycodes between 54 and 62 (with 57 being unaccounted for...).

This is on macOS 10.14 using official SC 3.12.1.

Additionally, the actual keys (not the modifiers) printed with the "You pressed" message are incorrect. I tried to rectify that, but couldn't find a reliable solution (using unicode `.asAscii` instead of keycode works for most cases, but not when keys are pressed with ctrl...). This is just cosmetic though. The main issue is that learning doesn't seem to currently work on macOS with the current version of SC (QT?).

Oh, the joys of multiplatform implementations :/

Would you like me to submit a PR with the proposed solution for the modifier key distinction?

**Comment by dyfer** [comment]
@jamshark70 should I submit a PR with the proposed workaround? I'd like to get this operational on macOS. Thanks!

**Comment by jamshark70** [comment]
> Here's my workaround in https://github.com/jamshark70/ddwSnippets/blob/master/ddwSnippets.sc#L264: { \osx } { { |char, keycode| (keycode >= 62) or: (keycode <= 54) } }. I'm not sure this is reliable, but it seems the modifiers (left/right shift, alt, ctrl, cmd) emit keycodes between 54 and 62 (with 57 being unaccounted for...).

I guess this is OK, though it should be `{ \osx } { { |char, keycode| (keycode > 62) or: (keycode < 54) } }`, right?

I have no way to test in Mac.

Let's go ahead with a PR... thanks!

**Comment by dyfer** [comment]
> I guess this is OK, though it should be `{ \osx } { { |char, keycode| (keycode > 62) or: (keycode < 54) } }`, right?

Yes, thanks for catching that.
I've submitted the PR. It seems to be working fine - I was able to set both ``ctrl-` `` and ``cmd-alt-` `` as hotkeys.

If you have ideas about what to experiment with to properly post the keys pressed, I'd be happy to test this on macOS. However I don't know what's the supposed translation of keycodes to ASCII...
